export const meetingsData = [
  {
    id: 1,
    title: "Project Kickoff",
    date: "2023-11-01",
    time: "10:00:00",
    duration: 60,
    attendees: "Alice, Bob, Charlie",
    description: "Initial project kickoff meeting",
  },
  {
    id: 2,
    title: "Weekly Sync",
    date: "2023-11-08",
    time: "14:00:00",
    duration: 30,
    attendees: "Alice, Bob",
    description: "Weekly team sync-up",
  },
  {
    id: 3,
    title: "Client Presentation",
    date: "2023-11-15",
    time: "09:00:00",
    duration: 90,
    attendees: "Alice, Charlie",
    description: "Presentation to the client about project progress",
  },
  {
    id: 4,
    title: "Retrospective",
    date: "2023-11-22",
    time: "16:00:00",
    duration: 45,
    attendees: "Bob, Charlie",
    description: "Sprint retrospective meeting",
  },
  {
    id: 5,
    title: "Team Building",
    date: "2023-11-29",
    time: "11:00:00",
    duration: 120,
    attendees: "Alice, Bob, Charlie, David",
    description: "Team building activities to enhance collaboration"
  },
  {
    id: 6,
    title: "Project Review",
    date: "2023-12-06",
    time: "15:00:00",
    duration: 60,
    attendees: "Alice, Bob, Charlie, David, Eve",
    description: "Review of project milestones and deliverables",
  },
  {
    id: 7,
    title: "Final Presentation",
    date: "2023-12-13",
    time: "10:00:00",
    duration: 90,
    attendees: "Alice, Bob, Charlie, David, Eve, Frank",
    description: "Final presentation of the project to stakeholders",
  },
];

// CREATE TABLE meetings (
//   id SERIAL PRIMARY KEY,
//   title VARCHAR(255),
//   date DATE,
//   time TIME,
//   duration INT,
//   attendees TEXT,
//   description TEXT
// );
